### ISSUE TITLE
検索文字列に記号が含まれている場合に検索文字列がおかしくなることがある

### ISSUE THREAD

**Issue by mapk0y** [eetann/amazing-searcher#52]
# 概要

記号が検索文字列に含まれている状態で検索（例えば `foo#bar` など）を行った場合に Amazing Searcher での期間指定を行うと、記号より後ろの文字列が消えてしまった検索（ `foo#bar` の場合は `foo` となる）になったり、異なった文字列（`foo%bar` の場合は `fooｺr` となる）になってしまったりします。

確認した範囲で検索文字列がおかしくなってしまう記号は `#` `&` `%` になります。
おそらく urlencode したら良いのだと思いますが、どの記号を urlencode するべきかが Google の提供する[ドキュメント](https://developers.google.com/custom-search/docs/xml_results_appendices?hl=en#url-escaping)と実際の挙動（下記に記述）とで異なるようです。

## 調査

`foo記号bar` という検索結果から Google 検索での期間指定を行った場合の挙動と Amazing Searcher での挙動について主な記号で一覧にしてみました。太字が挙動が異なるところになっています。

検索文字列|Google検索での検索ボックスの文字列|Google検索での QueryStrings|Amazing Searcher での検索ボックスの文字列|Amazing Searcherでの QueryStrings
:----|:----|:----|:----|:----
foo bar|foo bar|q=foo+bar&tbs=qdr:m|foo bar|q=foo%20bar&tbs=qdr:m1
foo!bar|foo!bar|q=foo!bar&tbs=qdr:m|foo!bar|q=foo!bar&tbs=qdr:m1
foo"bar|foo"bar|q=foo"bar&tbs=qdr:m|foo"bar|q=foo"bar&tbs=qdr:m1
foo#bar|foo#bar|q=foo%23bar&tbs=qdr:m|**foo**|**q=foo#bar&tbs=qdr:m1**
foo$bar|foo$bar|q=foo%24bar&tbs=qdr:m|foo$bar|**q=foo$bar&tbs=qdr:m1**
foo%bar|foo%bar|q=foo%25bar&tbs=qdr:m|**fooｺr** <sup>[1](#footnote1)</sup>|**q=foo%bar&tbs=qdr:m1**
foo&bar|foo&bar|q=foo%26bar&tbs=qdr:m|**foo**|**q=foo&bar&tbs=qdr:m1**
foo'bar|foo'bar|q=foo%27bar&tbs=qdr:m|foo'bar|q=foo%27bar&tbs=qdr:m1
foo(bar|foo(bar|q=foo(bar&tbs=qdr:m|foo(bar|q=foo(bar&tbs=qdr:m1
foo)bar|foo)bar|q=foo)bar&tbs=qdr:m|foo)bar|q=foo)bar&tbs=qdr:m1
foo*bar|foo*bar|q=foo*bar&tbs=qdr:m|foo*bar|q=foo*bar&tbs=qdr:m1
foo+bar|foo+bar|q=foo%2Bbar&tbs=qdr:m|**foo bar**|**q=foo+bar&tbs=qdr:m1**
foo,bar|foo,bar|q=foo,bar&tbs=qdr:m|foo,bar|q=foo,bar&tbs=qdr:m1
foo/bar|foo/bar|q=foo/bar&tbs=qdr:m|foo/bar|q=foo/bar&tbs=qdr:m1
foo:bar|foo:bar|q=foo:bar&tbs=qdr:m|foo:bar|q=foo:bar&tbs=qdr:m1
foo;bar|foo;bar|q=foo%3Bbar&tbs=qdr:m|foo;bar|**q=foo;bar&tbs=qdr:m1**
foo<bar|foo<bar|q=foo<bar&tbs=qdr:m|foo<bar|q=foo<bar&tbs=qdr:m1
foo=bar|foo=bar|q=foo%3Dbar&tbs=qdr:m|foo=bar|**q=foo=bar&tbs=qdr:m1**
foo>bar|foo>bar|q=foo>bar&tbs=qdr:m|foo>bar|q=foo>bar&tbs=qdr:m1
foo?bar|foo?bar|q=foo%3Fbar&tbs=qdr:m|foo?bar|**q=foo?bar&tbs=qdr:m1**
foo@bar|foo@bar|q=foo%40bar&tbs=qdr:m|foo@bar|**q=foo@bar&tbs=qdr:m1**
foo[bar|foo[bar|q=foo%5Bbar&tbs=qdr:m|foo[bar|**q=foo[bar&tbs=qdr:m1**
foo]bar|foo]bar|q=foo%5Dbar&tbs=qdr:m|foo]bar|**q=foo]bar&tbs=qdr:m1**
foo^bar|foo^bar|q=foo%5Ebar&tbs=qdr:m|foo^bar|**q=foo^bar&tbs=qdr:m1**
foo`bar|foo`bar|q=foo%60bar&tbs=qdr:m|foo`bar|**q=foo`bar&tbs=qdr:m1**
foo{bar|foo{bar|q=foo%7Bbar&tbs=qdr:m|foo{bar|**q=foo{bar&tbs=qdr:m1**
foo\|bar|foo\|bar|q=foo%7Cbar&tbs=qdr:m|foo\|bar|**q=foo\|bar&tbs=qdr:m1**
foo}bar|foo}bar|q=foo%7Dbar&tbs=qdr:m|foo}bar|**q=foo}bar&tbs=qdr:m1**
foo~bar|foo~bar|q=foo~bar&tbs=qdr:m|foo~bar|q=foo~bar&tbs=qdr:m1

<a name="footnote1">*1</a>: `%ba` がシフトJISでは半角カタカナの `ｺ` になる

## その他

同じ検索内容でもまれに urlencode した URL への 302 リダイレクトが行われることがありました。

例えば `foo{bar` の検索結果から Amazing Sercher の `m1` ボタンを押した場合のリクエストが以下のようになる場合がありました。

```
Request URL: https://www.google.com/search?q=foo{bar&tbs=qdr:m1
Status Code: 302 
Response Headers:
  location: https://www.google.com/search?q=foo%7Bbar&tbs=qdr:m1&sxsrf=XXXXXX&sec_act=sr
```

通常は以下のようになります。

```
Request URL: https://www.google.com/search?q=foo{bar&tbs=qdr:m1
Status Code: 200
```

この挙動になる条件はわかりませんでしたが動作確認される際はご注意ください。

**Comment by eetann** [comment]
@mapk0y 報告並びに調査のほど、本当にありがとうございます。
ご指摘の通り期間指定と言語指定の検索を行う際のエンコードを忘れていたため、修正いたします。

**Comment by mapk0y** [comment]
迅速な対応ありがとうございました :bow:
手元でも修正を確認したのでクローズしておきます
